#!/usr/bin/env ruby

require "optparse"
require "vernier/version"

module Vernier
  module CLI
    def self.run(options)
      banner = <<-END
Usage: vernier run [FLAGS] -- COMMAND

FLAGS:
      END

      OptionParser.new(banner) do |o|
        o.version = Vernier::VERSION

        o.on('--output [FILENAME]', String, "output filename") do |s|
          options[:output] = s
        end
        o.on('--interval [MICROSECONDS]', Integer, "sampling interval (default 500)") do |i|
          options[:interval] = i
        end
        o.on('--allocation-interval [ALLOCATIONS]', Integer, "allocation sampling interval (default 0 disabled)") do |i|
          options[:allocation_interval] = i
        end
        o.on('--signal [NAME]', String, "specify a signal to start and stop the profiler") do |s|
          options[:signal] = s
        end
        o.on('--start-paused', "don't automatically start the profiler") do
          options[:start_paused] = true
        end
        o.on('--hooks [HOOKS]', String, "enable instrumentation hooks, currently supported: rails") do |s|
          options[:hooks] = s
        end
      end
    end

    def self.view(options)
      banner = <<-END
Usage: vernier view [FLAGS] -- FILENAME

FLAGS:
      END

      OptionParser.new(banner) do |o|
        o.on('--top [COUNT]', Integer, "number of frames to show (default 20)") do |i|
          options[:top] = i
        end
      end
    end

    def self.inverted_tree(top, file)
      # Print the inverted tree from a Vernier profile
      require "json"

      is_gzip = File.binread(file, 2) == "\x1F\x8B".b # check for gzip header

      json = if is_gzip
        require "zlib"
        Zlib::GzipReader.open(file) { |gz| gz.read }
      else
        File.read file
      end

      info = JSON.load json

      main = info["threads"].find { |thread| thread["isMainThread"] }

      weight_by_frame = Hash.new(0)

      stack_frames = main["stackTable"]["frame"]
      frame_table = main["frameTable"]["func"]
      func_table = main["funcTable"]["name"]
      string_array = main["stringArray"]

      main["samples"]["stack"].zip(main["samples"]["weight"]).each do |stack, weight|
        top_frame_index = stack_frames[stack]
        func_index = frame_table[top_frame_index]
        string_index = func_table[func_index]
        str = string_array[string_index]
        weight_by_frame[str] += weight
      end

      total = weight_by_frame.values.inject :+

      header = ["Samples", "%", ""]
      widths = header.map(&:bytesize)

      columns = weight_by_frame.sort_by { |k,v| v }.reverse.first(top).map { |k,v|
        entry = [v.to_s, ((v / total.to_f) * 100).round(1).to_s, k]
        entry.each_with_index { |str, i| widths[i] = str.bytesize if widths[i] < str.bytesize }
        entry
      }

      print_separator widths
      print_row header, widths
      print_separator widths
      columns.each { print_row(_1, widths) }
      print_separator widths
    end

    def self.print_row(list, widths)
      puts("|" + list.map.with_index { |str, i| " " + str.ljust(widths[i] + 1) }.join("|") + "|")
    end

    def self.print_separator(widths)
      puts("+" + widths.map { |i| "-" * (i + 2) }.join("+") + "+")
    end

    def self.open(options)
      banner = <<-END
Usage: vernier open [FLAGS] -- FILENAME

FLAGS:
      END

      OptionParser.new(banner) do |o|
        o.on('--print', "print the url instead of opening it") do
          options[:print] = true
        end
      end
    end

    def self.serve_profile(profile_path)
      require 'socket'

      profile_server = TCPServer.new('localhost', 0)

      profile_server_thread = Thread.new do
        Thread.current.abort_on_exception = true
        loop do
          client = profile_server.accept
          request = client.gets

          next unless request&.start_with?('GET')

          File.open(profile_path, 'rb') do |file|
            is_gzip = file.read(2) == "\x1F\x8B".b
            file.rewind

            client.print("HTTP/1.1 200 OK\r\n")
            client.print("Content-Type: application/json\r\n")
            client.print("Access-Control-Allow-Origin: *\r\n")
            client.print("Content-Length: #{file.size}\r\n")
            client.print("Content-Encoding: gzip\r\n") if is_gzip
            client.print("\r\n")

            IO.copy_stream(file, client)
          end

          break
        ensure
          client&.close
        end
      end

      profile_server_port = profile_server.addr[1]
      profile_server_url = "http://localhost:#{profile_server_port}"

      begin
        success = yield profile_server_url
        profile_server_thread.kill unless success
        success
      ensure
        profile_server_thread.join unless profile_server_thread.status.nil?
        profile_server.close
      end
    end

    def self.open_url(url)
      require 'rbconfig'

      os = RbConfig::CONFIG['host_os']
      case os
      when /linux|bsd/
        system('xdg-open', url)
      when /darwin/
        system('open', url)
      when /mswin|mingw|cygwin/
        system('start', url)
      else
        warn("unsupported os: #{os}")
        false
      end
    end
  end
end

options = {}
run = Vernier::CLI.run(options)
view = Vernier::CLI.view(options)
open = Vernier::CLI.open(options)

case ARGV.shift
when "run"
  run.parse!
  run.abort(run.help) if ARGV.empty?

  env = {}
  options.each do |k, v|
    env["VERNIER_#{k.to_s.upcase}"] = v.to_s
  end
  vernier_path = File.expand_path('../lib', __dir__)
  env['RUBYOPT'] = "-I #{vernier_path} -r vernier/autorun #{ENV['RUBYOPT']}"

  Kernel.exec(env, *ARGV)
when "view"
  view.parse!
  view.abort(view.help) if ARGV.empty?
  Vernier::CLI.inverted_tree(options[:top] || 20, ARGV.shift)
when "open"
  open.parse!
  open.abort(open.help) if ARGV.empty?

  success = Vernier::CLI.serve_profile(ARGV.shift) do |profile_url|
    require 'uri'
    vernier_url = ENV.fetch('VERNIER_WEB_ENDPOINT', 'https://vernier.prof')
    vernier_profile_url = "#{vernier_url}/from-url/#{URI.encode_www_form_component(profile_url)}"
    if options[:print]
      puts(vernier_profile_url)
      true
    else
      Vernier::CLI.open_url(vernier_profile_url)
    end
  end

  Kernel.exit(1) unless success
else
  run.abort(run.help + "\n" + view.help + "\n" + open.help)
end
