
name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'What version level of bump?'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch


permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: Set git config
      run: |
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        git remote set-url origin "https://x-access-token:${{ github.token }}@github.com/$GITHUB_REPOSITORY"
      shell: bash
    - name: Bump version
      run: gem exec bump ${{ github.event.inputs.version }}
    - name: push
      run: git push
